# TODO: 需修改的配置，用于上传到 CloudFlare
name = "blogroll"
type = "webpack"
account_id = "ed02115b0333e518a62d649ee291264b"
workers_dev = true
# route = "blogroll.icl.moe/*"
zone_id = "374cfa163417e4f4a64edb66a0ddc218"

[site]
bucket = "./web/dist"
entry-point = "workers-site"
